### ISSUE TITLE
Error compiling to wasm target. Inclusion of getrandom is causing issues.

### ISSUE THREAD

**Issue by ewoolsey** [CosmWasm/cw-storage-plus#19]
I don't know how I'm the only one to have this issue, but when compiling with `cw-storage-plus = "1.0.0"` as a regular dependency it is trying to pull in getrandom. I think perhaps getrandom should probably be a dev dependency.

Exact error message is
```
error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /Users/ewoolsey/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/lib.rs:263:9
    |
263 | /         compile_error!("the wasm32-unknown-unknown target is not supported by \
264 | |                         default, you may need to enable the \"js\" feature. \
265 | |                         For more information see: \
266 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/ewoolsey/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.8/src/lib.rs:290:5
    |
290 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
process exited unsuccessfully: exit status: 101
```

This error only occurs using a wasm target. There is a super hacky workaround which is put this in your toml:
```toml
getrandom = { version = "0.2", features = ["js"] }
cw-storage-plus = "1"
```

**Comment by ewoolsey** [comment]
For more context, when building my project with `cw-storage-plus = "0.16.0"` everything works fine. Change the dependency to `cw-storage-plus = "1.0.0"` causes the error you see above.

**Comment by mikedotexe** [comment]
I can confirm this is happening in my project, too, which is an ultra-simple smart contract example.
I see there has been discussion about a similar problem when searching through the CosmWasm Discord, but seems like this issue describes the introduction of a small regression perhaps. 

All in all, very excited for the major version release! 🥳

**Comment by webmaster128** [comment]
Are you using resolver version 2? Are you in single contract projects or workspaces?

**Comment by PFC-developer** [comment]
i'm not sure about the resolver, but I was a workspaces when I saw it.

**Comment by ewoolsey** [comment]
I am in a large workspaces project. I'll switch to resolver v2 and report back.

**Comment by ewoolsey** [comment]
So I am using edition = "2021" which implies resolver = "2". So yes I am using the new resolver.

**Comment by webmaster128** [comment]
For workspaces you need to set the resolver explicitly, see https://github.com/CosmWasm/cosmwasm/blob/43cbe248a/Cargo.toml#L5-L7. This should avoid the problem.

But we can also get rid of the getrandom dependency here to make things easier.

**Comment by webmaster128** [comment]
@ewoolsey can you test if #20 did the trick (i.e. solve the problem no matter which resolver is used)? Just use cw-storage-plus from latest main.

**Comment by ewoolsey** [comment]
I just checked, and it appears that did not solve the problem. In my toml I have
```toml
cw-storage-plus = { git = "https://github.com/CosmWasm/cw-storage-plus" }
```
I can also confirm that even if I manually specify the resolver, it still does not compile. The only fix that's working for me is
```toml
getrandom = { version = "0.2", features = ["js"] }
```

**Comment by webmaster128** [comment]
Turns out the [explicit k256 dependency](https://github.com/CosmWasm/cw-storage-plus/blob/v1.0.0/Cargo.toml#L31-L34) was not a good idea. We need to remove it.

The error can also be reproduced in this repo directly by just running `cargo build --target wasm32-unknown-unknown`.

#23 should fix this.

**Comment by apollo-sturdy** [comment]
@webmaster128 Should `cw-storage-plus 1.0.0` perhaps be yanked?

**Comment by webmaster128** [comment]
Perhaps. I'm not sure about yanking policies in general. There is nothing horribly wrong about cw-storage-plus 1.0.0. I mean it contains no spyware or stuff. It just can't be compiled to the Wasm target. So it contains a bug and patch versions are there to fix bugs.

But I would say that this shows you should set a full version in your dependencies. While `cw-storage-plus = "1"` might look nice and simple, it is the wrong minimum and your project needs `cw-storage-plus = "1.0.1"`.

Same story for cw-utils 1.0.0 by the way.
