### ISSUE TITLE
Add a method to delete all Map elements under a prefix

### ISSUE THREAD

**Issue by larry0x** [CosmWasm/cw-storage-plus#29]
Now we have `Map::clear` method which deletes all elements in the map, it'd be helpful to also have a `Prefix::clear` method to delete all elements under a specific prefix, for example:

```rust
// (first name, last name) -> Person
const PERSONS: Map<(&str, &str), Person> = Map::new("persons");

// delete all persons whose first name is larry
PERSONS.prefix("larry").clear(&mut storage);
```

The same can be done for the `is_empty` method:

```rust
// check whether there are persons whose first name is larry
PERSONS.prefix("larry").is_empty(storage);
```

**Comment by larry0x** [comment]
@webmaster128 @ueco-jb  I did a quick and dirty implementation here: https://github.com/CosmWasm/cw-storage-plus/compare/main...steak-enjoyers:cw-storage-plus:prefix-clear

The idea is that `clear` and `is_empty` methods are moved into `Prefix`, while for `Map`, simply do:

```rust
impl Map {
    pub fn clear(&self, store: &mut dyn Storage) {
        self.no_prefix_raw().clear(store)
    }

    pub fn is_empty(&self, store: &dyn Storage) -> bool {
        self.no_prefix_raw().is_empty(store)
    }
}
```

I consider this implementation "dirty" because here:

```rust
impl Prefix {
    pub fn clear(&self, store: &mut dyn Storage) {
        const TAKE: usize = 10;
        let mut cleared = false;

        while !cleared {
            let paths = self
                .keys_raw(store, None, None, Order::Ascending)         // (1)
                .map(|raw_key| concat(&self.storage_prefix, &raw_key)) // (2)
                .take(TAKE)
                .collect::<Vec<_>>();

            paths.iter().for_each(|path| store.remove(path));

            cleared = paths.len() < TAKE;
        }
    }
}
```

On line (1), in `keys_raw` function, it trims off the prefix from the full path, while on line (2) we have to add the prefix right back, so this is a bunch of necessary computations.

Thoughts?

**Comment by webmaster128** [comment]
Sounds all good to me. I think one think we should introduce here is an optional limit for removals. Otherwise you can never support cases where the overall gas consumtion does not fit in a block. By keeping the limit optional, the existing Map.clear() can be supported by the same implementation in a compatible way.

**Comment by webmaster128** [comment]
@larry0x could you have a look at https://github.com/CosmWasm/cw-storage-plus/pull/45 and double check if this is what you are looking for?
