### ISSUE TITLE
implementation of KeyDeserialize for (T, U) is incorrect.

### ISSUE THREAD

**Issue by ewoolsey** [CosmWasm/cw-storage-plus#33]
Okay, so this is pretty complicated but I'll do my best to describe the bug using an example. Here is an example impl of KeyDeserialize and Primary key for an enum:

```rust
#[cw_serde]
#[repr(u8)]
#[derive(Eq, PartialOrd, Ord)]
pub enum AssetInfo {
    Token { contract_addr: Addr },
    NativeToken { denom: String },
}

const NATIVE_TOKEN_DISCRIMINANT: u8 = 0;
const TOKEN_DISCRIMINANT: u8 = 1;

impl<'a> PrimaryKey<'a> for &'a AssetInfo {
    type Prefix = u8;
    type SubPrefix = ();
    type Suffix = String;
    type SuperSuffix = Self;

    fn key(&self) -> Vec<Key> {
        // The discriminate is added as a prefix.
        match self {
            AssetInfo::Token { contract_addr: addr } => {
                vec![Key::Val8([TOKEN_DISCRIMINANT]), Key::Ref(addr.as_bytes())]
            }
            AssetInfo::NativeToken { denom } => {
                vec![Key::Val8([NATIVE_TOKEN_DISCRIMINANT]), Key::Ref(denom.as_bytes())]
            }
        }
    }
}

impl<'a> KeyDeserialize for &'a AssetInfo {
    type Output = AssetInfo;

    #[inline(always)]
    fn from_vec(mut value: Vec<u8>) -> StdResult<Self::Output> {
        // The discriminate is the first byte after the prefix.
        // Split off after the 3rd.
        let split = value.split_off(3);

        // Pop off the last byte (3rd) in value which is the discriminate.
        match value.pop().unwrap() {
            TOKEN_DISCRIMINANT => Ok(AssetInfo::Token { contract_addr: Addr::from_vec(split)? }),
            NATIVE_TOKEN_DISCRIMINANT => Ok(AssetInfo::NativeToken { denom: String::from_vec(split)? }),
            _ => Err(StdError::GenericErr { msg: "Failed deserializing.".into() }),
        }
    }
}
```

Using this code, we can effectively save and load from storage and iterate through the map when we have the type
`Map<&AssetInfo, T>`, But, when we use the type `Map<(&AssetInfo, &AssetInfo), String>` we run into some problems. We can still save and load from storage no problem, but iterating though the map causes a panic inside the `from_vec` implementation above, with the msg:
`thread 'asset::test::test_tuple_key_serialize_deserialzie' panicked at '`at` split index (is 3) should be <= len (is 1)', library/alloc/src/vec/mod.rs:2110:13`

If you write a few items to storage then call
```rust
map.range(deps.storage, None, None, Order::Ascending).collect::<Result<Vec<_>, _>>()?
```
it panics. Here is a test you can try
```rust
    #[test]
    fn test_tuple_key_serialize_deserialzie() {
        let mut owned_deps = mock_dependencies();
        let deps = owned_deps.as_mut();
        pub const ASSET_TUPLE: cw_storage_plus::Map<(&AssetInfo, &AssetInfo), String> =
            cw_storage_plus::Map::new("asset_tuple");

        let native_token_1 = AssetInfo::NativeToken { denom: "utest1".into() };
        let native_token_2 = AssetInfo::NativeToken { denom: "utest2".into() };
        let token_1 = AssetInfo::Token { contract_addr: Addr::unchecked("my_address1") };
        let token_2 = AssetInfo::Token { contract_addr: Addr::unchecked("my_address2") };

        ASSET_TUPLE.save(deps.storage, (&token_1, &token_2), &"token_1,token_2".into()).unwrap();
        ASSET_TUPLE
            .save(deps.storage, (&native_token_1, &native_token_2), &"native_token_1,native_token_2".into())
            .unwrap();

        assert_eq!(ASSET_TUPLE.load(deps.storage, (&token_1, &token_2)).unwrap(), "token_1,token_2");
        assert_eq!(
            ASSET_TUPLE.load(deps.storage, (&native_token_1, &native_token_2)).unwrap(),
            "native_token_1,native_token_2"
        );

        let list = ASSET_TUPLE
            .range(deps.storage, None, None, Order::Ascending)
            .collect::<Result<Vec<_>, _>>()
            .unwrap();
        assert_eq!(list.len(), 4);
        // native tokens have a discriminate of 0 so are sorted first
        // assert_eq!(list[0].0, native_token_1);
        // assert_eq!(list[1].0, native_token_2);
        // assert_eq!(list[2].0, token_1);
        // assert_eq!(list[3].0, token_2);
    }
```

**Comment by maurolacy** [comment]
I think this happens because your `from_vec` impl is not generic enough to handle the 2nd `AssetInfo` inside the tuple, which is not length prefixed.

Just add a condition that if the length of `value` is less than 3, avoids the split, and you should be fine.

**Comment by ewoolsey** [comment]
Okay so here is an example demonstrating the same underlying issue but without the custom enum implementation. Here is an example using a tuple of tuples.

```rust
    #[test]
    fn test_tuple_tuple_key_serialize_deserialzie() {
        let mut owned_deps = mock_dependencies();
        let deps = owned_deps.as_mut();
        pub const ASSET_TUPLE: cw_storage_plus::Map<((String, String), (String, String)), String> =
            cw_storage_plus::Map::new("asset_tuple");

        let a = String::from("a");
        let b = String::from("a");
        let c = String::from("a");
        let d = String::from("a");

        ASSET_TUPLE.save(deps.storage, ((a, b), (c, d)), &"abcd".to_string()).unwrap();

        let list = ASSET_TUPLE
            .range(deps.storage, None, None, Order::Ascending)
            .collect::<Result<Vec<_>, _>>()
            .unwrap();
```
using the same logging as above it fails with this msg:
```
running 1 test
value (Tuple): [0, 1, 97, 0, 1, 97, 0, 1, 97, 97]
tu: [97, 0, 1, 97, 0, 1, 97, 97]
tu: [97]
t_len: 1
u: [0, 1, 97, 0, 1, 97, 97]
value (Tuple): [97]
thread 'asset::test::test_tuple_tuple_key_serialize_deserialzie' panicked at '`at` split index (is 2) should be <= len (is 1)', library/alloc/src/vec/mod.rs:2110:13
```

I think this is quite a serious issue.

**Comment by ewoolsey** [comment]
After some brainstorming on how to fix this, I don't think it can be fixed. I think the only solution is to entirely remove the blanket implementation. There is simply not enough information provided to from_vec to know how to generically deserialize. from_vec simply cannot know how many items within the byte array belong to which type (T or U). More information could be passed into from_vec, but that would require a very large refactor.

**Comment by maurolacy** [comment]
If you have something like `(String, String)` working properly, then it 
should be possible to make something like `(AssetInfo, AssetInfo)` behave.

Tuples of tuples may very well not be properly supported. We don't need 
to support all of the possible combinations of keys, tuples of tuples, 
etc. Only the ones that are useful / make sense.

**Comment by ewoolsey** [comment]
> If you have something like `(String, String)` working properly, then it should be possible to make something like `(AssetInfo, AssetInfo)` behave. Tuples of tuples may very well not be properly supported.

I disagree. AssetInfo is an enum, which is functionally the same as a tuple in this case. This is because you must supply a Key for both the enum discriminate and the value of the variant. With the current implementation there is no way to make a (AssetInfo, AssetInfo) work properly.

> We don't need to support all of the possible combinations of keys, tuples of tuples, etc. Only the ones that are useful / make sense.

I think it's very bad form to provide a blanket implementation which is not correct in all cases, because:

1. It causes unexpected behaviour and massive headaches for devs who are confused why something isn't working (ask me how I know haha)
2. It prevents devs from overriding the incorrect impl with the correct one. It is now impossible for me to provide a correct implementation.

My team has spent 6 months working on a project that just completed audit only to just now find this bug. so I would definitely say that it is worth fixing.

**Comment by ewoolsey** [comment]
A possible solution to this issue is to create a new trait `SimplePrimaryKey` with the same form as PrimaryKey except that `key()` returns a `Key` instead of a `Vec<Key>`. Then provide a blanket impl so that all `SimplePrimaryKey` also are `PrimaryKey`. Then change the implementation of all the simple (non compound) types to `SimplePrimaryKey`. Finally, we add the trait bounds to 
```rust
impl<T: SimplePrimaryKey + ..., U: SimplePrimaryKey + ...>  KeyDeserialize for (T,U)
```

This has the huge advantage of not introducing any breaking api changes. If I could get approval from someone on the project I would be happy to work on a PR.

**Comment by maurolacy** [comment]
Feel free to work on that and I can review it; can merge it if we agree it's a sensible and worthwhile solution, as usual.

That said, I still think that it should be possible to avoid this issue by changing the `AssetInfo` impl of `key()` and `from_vec()`.  Will work on it next week, when finding some time.

**Comment by maurolacy** [comment]
> That said, I still think that it should be possible to avoid this issue by changing the `AssetInfo` impl of `key()` and `from_vec()`. Will work on it next week, when finding some time.

Was playing with this, and I agree that the only way to encode an enum seems to be by using multiple elements (because `Val`s can only be fixed-size arrays). And then this issue appears.

I think tackling this with the proposal you made is a good way to go. If you provide an PR, we'll carefully consider it. Thanks.

**Comment by maurolacy** [comment]
Another (simpler?) way to solve this is add a `Val(Vec<u8>),` variant to `Key`, and use the owned variable-length variant to implement `AssetInfo` serialisation / deserialisation.

**Comment by ewoolsey** [comment]
I had considered that as a solution to my individual problem, but it doesn't actually solve the general incorrectness of the blanket impl, which I do think should be fixed.

**Comment by ewoolsey** [comment]
I'm running into a slight problem here
```rust
pub(crate) struct Snapshot<'a, K, T> {
    checkpoints: Map<'a, u64, u32>,

    // this stores all changes (key, height). Must differentiate between no data written,
    // and explicit None (just inserted)
    pub changelog: Map<'a, (K, u64), ChangeSet<T>>,

    // How aggressive we are about checkpointing all data
    strategy: Strategy,
}
```
Snapshot is defined in a problematic way. If K is not SimpleKey then it has an invalid implementation. With the way the current implementation is right now, For `(T, U)`, `T` must be `SimplePrimaryKey` while `U` may be allowed to just be `PrimaryKey`. We could change the order of the tuple, but we would likely have to break semver for that...

**Comment by ewoolsey** [comment]
So I have another idea that I think will solve all our problems. We leave everything alone except for KeyDeserialize where we add the associate constant `const KEY_LEN: u16;`. we can set the default to be `const KEY_LEN: u16 = 1` which will avoid compilation errors for external projects, but is less correct and could easily lead to bugs for people that use the lib.

Now we can use KEY_LEN to properly impl KeyDeserialize for (T, U) and (T, U, V). Yay! I think by far this is the simplest approach that leads to the least amount of overhauled code and breaking changes. Working on a PR now.

**Comment by ewoolsey** [comment]
pull request is here #34
