### ISSUE TITLE
No easy way of finding for an existing element in `Deque` (like `VecDeque.contains()`)

### ISSUE THREAD

**Issue by taitruong** [CosmWasm/cw-storage-plus#52]
Would be similar to `VecDeque.contains()`: https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.contains

Afaik there are only to options for checking an existing element in `Deque`:

```rust
// option 1: `find()` directly on Deque, but here element is `Deque`
let option1 = DEQUE
    .iter(storage)
    .into_iter()
    .find(|deque_iter| {
        deque_iter
            .find(|result| result.map(|e| e == value).is_ok())
            .is_some()
    })
    .is_some();
// option 2: collect all data (`Vect[T]`) on `Deque`, then `find()` on Vec uses `contains`
let option2 = DEQUE
    .iter(storage)?
    .collect::<StdResult<Vec<T>>>()
    .iter()
    .find(|e| e.contains(&value))
    .is_some();
```
Looks like there is no better way than doing it this way. Probably option 1 is better in performance than 2, since option2 requires to collect all data first.

**Comment by chipshort** [comment]
This has O(n) complexity. Doing this in a smart contract where the deque size can be influenced by users can lead to prohibitively high gas cost.
If you need this check, you probably want to use a different kind of data structure.

**Comment by webmaster128** [comment]
VecDeque is an in-memory datastructure but Deque is a storage helper. Implementing `contains` will easily be very slow. I don't think we should encourage this usage.

What's the use case in which you need to check element existence? You probably want a sorted data type such that you can do binary search.

**Comment by webmaster128** [comment]
Closing as stale. Feel free to re-open and explain the full use case. Then we can try to think about a better solution.
