### ISSUE TITLE
Confirmation of the feasibility of nested Map.

### ISSUE THREAD

**Issue by 99Kies** [CosmWasm/cw-storage-plus#72]
Does cosmwasm support this kind of map writing, I want to implement this kind of nested map, how should I do **save**, **load**, **update** and **remove**.

```rust
Map<&u128, Map<&Addr, Uint128>>
```

---

I want to implement this data structure that.

```javascript
{
    index_1: {
        user_addr_1: claimable_amount,
        user_addr_2: claimable_amount,
    },
    index_2: {
        user_addr_1: claimable_amount,
        user_addr_2: claimable_amount,
        user_addr_3: claimable_amount,
    }
}
```

**Comment by 99Kies** [comment]
@maurolacy bro, I need help. thanks! 🙏

**Comment by hashedone** [comment]
@99Kies @maurolacy is not actively maintaining storage-plus right now. He moved to another project.

Answering your question - no, nested maps are not a thing. But what you can do is a compound key:

```
my_map: Map<(u128, &Addr), Uint128>>
```

With this, you can access the item indexed as `[15]["user_addr_1"]`:

```
my_map.load(deps.storage, (15, &Addr::unchecked("user_addr_1")))?;
```

And you can also iterate through all items from the '[18]` pool:

```
let items = my_map.prefix(18).range(deps.storage, None, None, Order::Ascending);
```

The `items` here would be an iterator yielding `(Addr, Uint128)` - the `Uint128` is the map's final value. 

The reason for that is, that the storage of CosmWasm is not structural at all - it is a flat key-value map. The storage-plus utilities, including Map are just accessors that do some key mapping to imitate a structure, but building arbitrary hierarchy is out of its scope. What we can do is build the key out of multiple parts (like a tuple), and use some iteration utilities to access them partially.

**Comment by 99Kies** [comment]
@hashedone  If in this case I want to remove the bound data under the specified index, Is there need to additionally store {index: user_list} and then do the removes one by one?

like this:

```rust

        let old_beneficiaries =
            REWARD_ADDR_SEQUENECE.load(deps.storage, &reward_sequenece_index)?;
        for i in 0..old_beneficiaries.len() {
            let old_beneficiary = &old_beneficiaries[i];
            REWARD_SEQUENECE.remove(deps.storage, (reward_sequenece_index, old_beneficiary));
        }
        REWARD_ADDR_SEQUENECE.remove(deps.storage, &reward_sequenece_index);
```

**Comment by 99Kies** [comment]
Is there any good way to do a unified CURD based on index data?

**Comment by maurolacy** [comment]
> Is there need to additionally store {index: user_list} and then do the removes one by one?

You cannot read and write over the same storage container at the same time. You don't need an additional container. You can collect all the items to remove in memory, and then loop over them to remove them.

**Comment by 99Kies** [comment]
like use this way. right? (I'm remove old REWARD_SEQUENECE data with REWARD_ADDR_SEQUENECE.) @maurolacy 

> @hashedone If in this case I want to remove the bound data under the specified index, Is there need to additionally store {index: user_list} and then do the removes one by one?
> 
> like this:
> 
> ```rust
>         let old_beneficiaries =
>             REWARD_ADDR_SEQUENECE.load(deps.storage, &reward_sequenece_index)?;
>         for i in 0..old_beneficiaries.len() {
>             let old_beneficiary = &old_beneficiaries[i];
>             REWARD_SEQUENECE.remove(deps.storage, (reward_sequenece_index, old_beneficiary));
>         }
>         REWARD_ADDR_SEQUENECE.remove(deps.storage, &reward_sequenece_index);
> ```
