### ISSUE TITLE
Add more Rust-like APIs to storage-plus Map

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-storage-plus#9]
`Map` is essentially `BTreeMap`, but it needs Storage as an argument, and it may return error.

We could use more similar naming (insert, get rather than save and load).
I would not change existing APIs, but rather add some other methods and see if they are easier for end users. Possibly deprecate the current ones in the future.

I have a few reservations as I think there are some subtle differences that may be more annoying if you have a name you recognise you expect it to behave the same. Let's try an see.

**Comment by uint** [comment]
Time has passed. The API is pretty set by now, and I don't think we're looking to develop this library other than to fix serious bugs/footguns.
